In [2]:
import numpy as np 

import pandas as pd

In [3]:
data_1 = {
    "ID" : [1,2,3],
    "Name" : ["Adi","Sham","Sai"]
}

In [4]:
print(type(data_1))

<class 'dict'>

In [5]:
data_1

{'ID': [1, 2, 3], 'Name': ['Adi', 'Sham', 'Sai']}

In [6]:
data_1 = pd.DataFrame(data_1)

data_1

   ID  Name
0   1   Adi
1   2  Sham
2   3   Sai

In [7]:
print(type(data_1))

<class 'pandas.core.frame.DataFrame'>

In [8]:
data_2 = {
    "ID" : [1,2,3],
    "City":["Pune","Nashik","Pune"],
    "Marks":[89,87,56]
}

In [9]:
data_2

{'ID': [1, 2, 3], 'City': ['Pune', 'Nashik', 'Pune'], 'Marks': [89, 87, 56]}

In [10]:
data_2 = pd.DataFrame(data_2)

In [11]:
data_1

   ID  Name
0   1   Adi
1   2  Sham
2   3   Sai

In [12]:
data_2

   ID    City  Marks
0   1    Pune     89
1   2  Nashik     87
2   3    Pune     56

In [13]:
data_all = pd.merge(data_1,data_2 , on="ID")

data_all

   ID  Name    City  Marks
0   1   Adi    Pune     89
1   2  Sham  Nashik     87
2   3   Sai    Pune     56

In [14]:
data_all["Name"]

0     Adi
1    Sham
2     Sai
Name: Name, dtype: object

In [15]:
data_all["City"]

0      Pune
1    Nashik
2      Pune
Name: City, dtype: object

In [16]:
New_data = data_all[["Name","ID","Marks"]]

In [17]:
New_data

   Name  ID  Marks
0   Adi   1     89
1  Sham   2     87
2   Sai   3     56

In [18]:
'''
D_1 = [Name , ID ]

D2  = [Name , City , Marks]

D3 = [ID,Grade]

master = [ID , Name , Marks , Grade , City ]

'''

'\nD_1 = [Name , ID ]\n\nD2  = [Name , City , Marks]\n\nD3 = [ID,Grade]\n\nmaster = [ID , Name , Marks , Grade , City ]\n\n'

In [19]:
d_1 = {
    "ID" : [1,2,3],
    "Name" : ["Adi","Sham","Sai"]
}

d_1 = pd.DataFrame(d_1)

In [20]:
d_2 = {
    "Name" : ["Adi","Sham","Sai"],
    "City":["Pune","Nashik","Pune"],
    "Marks":[89,87,56]   
}

d_2 = pd.DataFrame(d_2)

In [21]:
d_3 = {
     "ID" : [1,2,3],
     "Grade":["A","B","A"]
}

d_3 = pd.DataFrame(d_3)

In [22]:
d_1

   ID  Name
0   1   Adi
1   2  Sham
2   3   Sai

In [23]:
d_2

   Name    City  Marks
0   Adi    Pune     89
1  Sham  Nashik     87
2   Sai    Pune     56

In [24]:
d_3

   ID Grade
0   1     A
1   2     B
2   3     A

In [25]:
A = pd.merge(d_1,d_2,on="Name")

In [26]:
master = pd.merge(A,d_3,on="ID")

In [27]:
master

   ID  Name    City  Marks Grade
0   1   Adi    Pune     89     A
1   2  Sham  Nashik     87     B
2   3   Sai    Pune     56     A

In [28]:
master = master[["ID","Name","Marks","Grade","City"]]

master

   ID  Name  Marks Grade    City
0   1   Adi     89     A    Pune
1   2  Sham     87     B  Nashik
2   3   Sai     56     A    Pune

# basic EDA

In [29]:
df = pd.read_excel(r"C:\Users\Dell\Desktop\Excel Sheet\SuperStore Sales DataSet (4).xlsx")

In [31]:
df.shape

(5905, 22)

In [33]:
df.head(3)

,Row ID+O6G3A1:R6,Order ID,Order Date,Month,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode
0,4918.0,CA-2019-160304,2019-01-01,January,2019-01-07,Standard Class,BM-11575,Brendan Murry,Corporate,United States,...,East,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1.0,28.2668,0.0,Online
1,4919.0,CA-2019-160304,2019-01-02,January,2019-01-07,Standard Class,BM-11575,Brendan Murry,Corporate,United States,...,East,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3.0,38.2668,0.0,Online
2,4920.0,CA-2019-160304,2019-01-02,January,2019-01-07,Standard Class,BM-11575,Brendan Murry,Corporate,United States,...,East,TEC-PH-10000455,Technology,Phones,GE 30522EE2,231.98,2.0,67.2742,0.0,Cards

In [38]:
df.tail(5)

,Row ID+O6G3A1:R6,Order ID,Order Date,Month,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode
5900,5093.0,CA-2020-151450,2020-12-31,December,2021-01-04,Standard Class,JM-15580,Jill Matthias,Consumer,United States,...,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,2975.51,3.0,-0.6048,0.0,COD
5901,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5902,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5903,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5904,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,5754,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5905 entries, 0 to 5904
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID+O6G3A1:R6  5901 non-null   float64
 1   Order ID          5901 non-null   object
 2   Order Date        5901 non-null   datetime64[ns]
 3   Month             5901 non-null   object
 4   Ship Date         5901 non-null   datetime64[ns]
 5   Ship Mode         5901 non-null   object
 6   Customer ID       5901 non-null   object
 7   Customer Name     5901 non-null   object
 8   Segment           5902 non-null   object
 9   Country           5901 non-null   object
 10  City              5901 non-null   object
 11  State             5901 non-null   object
 12  Region            5901 non-null   object
 13  Product ID        5901 non-null   object
 14  Category          5901 non-null   object
 15  Sub-Category      5901 non-null   object
 16  Product Name      5901 non-null   object
 17  Sales             5901 non-null   float64
 18  Quantity          5901 non-null   float64
 19  Profit            5901 non-null   float64
 20  Returns           5901 non-null   float64
 21  Payment Mode      5901 non-null   object
dtypes: datetime64[ns](2), float64(5), object(15)
memory usage: 1015.1+ KB

In [40]:
pd.isnull(df).sum()

Row ID+O6G3A1:R6    4
Order ID            4
Order Date          4
Month               4
Ship Date           4
Ship Mode           4
Customer ID         4
Customer Name       4
Segment             3
Country             4
City                4
State               4
Region              4
Product ID          4
Category            4
Sub-Category        4
Product Name        4
Sales               4
Quantity            4
Profit              4
Returns             4
Payment Mode        4
dtype: int64

In [41]:
df.columns

Index(['Row ID+O6G3A1:R6', 'Order ID', 'Order Date', 'Month', 'Ship Date',
       'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country',
       'City', 'State', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Profit', 'Returns',
       'Payment Mode'],
      dtype='object')

# Basic DC

In [45]:
df.dropna(inplace=True)

In [46]:
pd.isnull(df).sum()

Row ID+O6G3A1:R6    0
Order ID            0
Order Date          0
Month               0
Ship Date           0
Ship Mode           0
Customer ID         0
Customer Name       0
Segment             0
Country             0
City                0
State               0
Region              0
Product ID          0
Category            0
Sub-Category        0
Product Name        0
Sales               0
Quantity            0
Profit              0
Returns             0
Payment Mode        0
dtype: int64

In [48]:
df.rename(columns={"Order ID":"OID"},inplace=True)

In [51]:
df.columns

Index(['Row ID+O6G3A1:R6', 'OID', 'Order Date', 'Month', 'Ship Date',
       'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country',
       'City', 'State', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Profit', 'Returns',
       'Payment Mode'],
      dtype='object')

In [53]:
df.rename(columns={"Product ID":"PID"},inplace=True)

In [55]:
df.drop('Row ID+O6G3A1:R6',axis=1,inplace=True)

In [56]:
df.columns

Index(['OID', 'Order Date', 'Month', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region', 'PID',
       'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity',
       'Profit', 'Returns', 'Payment Mode'],
      dtype='object')

# DF